### ISSUE TITLE
No support for 64-bit linux

### ISSUE THREAD

**Issue by joekrill** [flirc/flirc-xbmc-plugin#1]
The Libraries folder contains armv6l and i686 libraries but no x86_64, so this plugin will not work on 64 bit Linux system. A compiled libflirc.so for 64 bit Linux is needed.

**Comment by pieterh** [comment]
seems like an urgent issue for the openelec users, since from next release on only 64bit is supported.

**Comment by flirc** [comment]
We're alive, not to worry, I've got this done and we will push this in the next commit. Sean is going to make the push next week. Remember you can still pair your flirc elsewhere and use the device on your system without any software. Thanks for the heads up.

**Comment by pieterh** [comment]
good to hear! Just wanted you to notice it ;-) thanks for the quick support on the plugin.

**Comment by flirc** [comment]
Thanks Sean for the push, closed with b592f0319d2469b2f27118e57cb9805210d08c1d
